// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.2
// source: proto/orion_holepunch.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message sent to initialize a hole-punching session for a given Wireguard Tunnel.
type HolePunchingInitialize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *HolePunchingInitialize) Reset() {
	*x = HolePunchingInitialize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_orion_holepunch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HolePunchingInitialize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolePunchingInitialize) ProtoMessage() {}

func (x *HolePunchingInitialize) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orion_holepunch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolePunchingInitialize.ProtoReflect.Descriptor instead.
func (*HolePunchingInitialize) Descriptor() ([]byte, []int) {
	return file_proto_orion_holepunch_proto_rawDescGZIP(), []int{0}
}

func (x *HolePunchingInitialize) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

// Message send to inform the client of the Wireguard credentials and ip adresses
type HolePunchingInitializationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The public endpoint and port of the registry server.
	EndpointAddr string `protobuf:"bytes,1,opt,name=endpoint_addr,json=endpointAddr,proto3" json:"endpoint_addr,omitempty"`
	EndpointPort uint32 `protobuf:"varint,2,opt,name=endpoint_port,json=endpointPort,proto3" json:"endpoint_port,omitempty"`
	// The public key of the registry server.
	PublicKey []byte `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// The preshared key assigned by the server for this session.
	PresharedKey []byte `protobuf:"bytes,4,opt,name=preshared_key,json=presharedKey,proto3" json:"preshared_key,omitempty"`
}

func (x *HolePunchingInitializationResponse) Reset() {
	*x = HolePunchingInitializationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_orion_holepunch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HolePunchingInitializationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolePunchingInitializationResponse) ProtoMessage() {}

func (x *HolePunchingInitializationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orion_holepunch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolePunchingInitializationResponse.ProtoReflect.Descriptor instead.
func (*HolePunchingInitializationResponse) Descriptor() ([]byte, []int) {
	return file_proto_orion_holepunch_proto_rawDescGZIP(), []int{1}
}

func (x *HolePunchingInitializationResponse) GetEndpointAddr() string {
	if x != nil {
		return x.EndpointAddr
	}
	return ""
}

func (x *HolePunchingInitializationResponse) GetEndpointPort() uint32 {
	if x != nil {
		return x.EndpointPort
	}
	return 0
}

func (x *HolePunchingInitializationResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *HolePunchingInitializationResponse) GetPresharedKey() []byte {
	if x != nil {
		return x.PresharedKey
	}
	return nil
}

// Message send to inform that the information was gathered by the registry server
type HolePunchingCompleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientEndpoint string `protobuf:"bytes,1,opt,name=client_endpoint,json=clientEndpoint,proto3" json:"client_endpoint,omitempty"`
}

func (x *HolePunchingCompleteResponse) Reset() {
	*x = HolePunchingCompleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_orion_holepunch_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HolePunchingCompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolePunchingCompleteResponse) ProtoMessage() {}

func (x *HolePunchingCompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orion_holepunch_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolePunchingCompleteResponse.ProtoReflect.Descriptor instead.
func (*HolePunchingCompleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_orion_holepunch_proto_rawDescGZIP(), []int{2}
}

func (x *HolePunchingCompleteResponse) GetClientEndpoint() string {
	if x != nil {
		return x.ClientEndpoint
	}
	return ""
}

// Message after the connection of the client to the holepunching-dedicated server endpoint.
type HolePunchingEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//
	//	*HolePunchingEvent_InitializationResponse
	//	*HolePunchingEvent_Complete
	Event isHolePunchingEvent_Event `protobuf_oneof:"event"`
}

func (x *HolePunchingEvent) Reset() {
	*x = HolePunchingEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_orion_holepunch_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HolePunchingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolePunchingEvent) ProtoMessage() {}

func (x *HolePunchingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orion_holepunch_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolePunchingEvent.ProtoReflect.Descriptor instead.
func (*HolePunchingEvent) Descriptor() ([]byte, []int) {
	return file_proto_orion_holepunch_proto_rawDescGZIP(), []int{3}
}

func (m *HolePunchingEvent) GetEvent() isHolePunchingEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *HolePunchingEvent) GetInitializationResponse() *HolePunchingInitializationResponse {
	if x, ok := x.GetEvent().(*HolePunchingEvent_InitializationResponse); ok {
		return x.InitializationResponse
	}
	return nil
}

func (x *HolePunchingEvent) GetComplete() *HolePunchingCompleteResponse {
	if x, ok := x.GetEvent().(*HolePunchingEvent_Complete); ok {
		return x.Complete
	}
	return nil
}

type isHolePunchingEvent_Event interface {
	isHolePunchingEvent_Event()
}

type HolePunchingEvent_InitializationResponse struct {
	InitializationResponse *HolePunchingInitializationResponse `protobuf:"bytes,1,opt,name=initialization_response,json=initializationResponse,proto3,oneof"`
}

type HolePunchingEvent_Complete struct {
	Complete *HolePunchingCompleteResponse `protobuf:"bytes,2,opt,name=complete,proto3,oneof"`
}

func (*HolePunchingEvent_InitializationResponse) isHolePunchingEvent_Event() {}

func (*HolePunchingEvent_Complete) isHolePunchingEvent_Event() {}

var File_proto_orion_holepunch_proto protoreflect.FileDescriptor

var file_proto_orion_holepunch_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x72, 0x69, 0x6f, 0x6e, 0x5f, 0x68, 0x6f,
	0x6c, 0x65, 0x70, 0x75, 0x6e, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x37, 0x0a,
	0x16, 0x48, 0x6f, 0x6c, 0x65, 0x50, 0x75, 0x6e, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x69,
	0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0xb2, 0x01, 0x0a, 0x22, 0x48, 0x6f, 0x6c, 0x65, 0x50,
	0x75, 0x6e, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a,
	0x0d, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x41, 0x64,
	0x64, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x65, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x65, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x64, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x70,
	0x72, 0x65, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x4b, 0x65, 0x79, 0x22, 0x47, 0x0a, 0x1c, 0x48,
	0x6f, 0x6c, 0x65, 0x50, 0x75, 0x6e, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x64, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x22, 0xb9, 0x01, 0x0a, 0x11, 0x48, 0x6f, 0x6c, 0x65, 0x50, 0x75, 0x6e,
	0x63, 0x68, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x5e, 0x0a, 0x17, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x48, 0x6f,
	0x6c, 0x65, 0x50, 0x75, 0x6e, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61,
	0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x48, 0x00, 0x52, 0x16, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x08, 0x63, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x48,
	0x6f, 0x6c, 0x65, 0x50, 0x75, 0x6e, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x08, 0x63,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x32, 0x4f, 0x0a, 0x13, 0x48, 0x6f, 0x6c, 0x65, 0x50, 0x75, 0x6e, 0x63, 0x68, 0x69, 0x6e, 0x67,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x17, 0x2e, 0x48, 0x6f, 0x6c, 0x65, 0x50, 0x75, 0x6e, 0x63, 0x68, 0x69, 0x6e,
	0x67, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x1a, 0x12, 0x2e, 0x48, 0x6f,
	0x6c, 0x65, 0x50, 0x75, 0x6e, 0x63, 0x68, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x30,
	0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_orion_holepunch_proto_rawDescOnce sync.Once
	file_proto_orion_holepunch_proto_rawDescData = file_proto_orion_holepunch_proto_rawDesc
)

func file_proto_orion_holepunch_proto_rawDescGZIP() []byte {
	file_proto_orion_holepunch_proto_rawDescOnce.Do(func() {
		file_proto_orion_holepunch_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_orion_holepunch_proto_rawDescData)
	})
	return file_proto_orion_holepunch_proto_rawDescData
}

var file_proto_orion_holepunch_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_orion_holepunch_proto_goTypes = []interface{}{
	(*HolePunchingInitialize)(nil),             // 0: HolePunchingInitialize
	(*HolePunchingInitializationResponse)(nil), // 1: HolePunchingInitializationResponse
	(*HolePunchingCompleteResponse)(nil),       // 2: HolePunchingCompleteResponse
	(*HolePunchingEvent)(nil),                  // 3: HolePunchingEvent
}
var file_proto_orion_holepunch_proto_depIdxs = []int32{
	1, // 0: HolePunchingEvent.initialization_response:type_name -> HolePunchingInitializationResponse
	2, // 1: HolePunchingEvent.complete:type_name -> HolePunchingCompleteResponse
	0, // 2: HolePunchingService.Session:input_type -> HolePunchingInitialize
	3, // 3: HolePunchingService.Session:output_type -> HolePunchingEvent
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_orion_holepunch_proto_init() }
func file_proto_orion_holepunch_proto_init() {
	if File_proto_orion_holepunch_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_orion_holepunch_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HolePunchingInitialize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_orion_holepunch_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HolePunchingInitializationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_orion_holepunch_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HolePunchingCompleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_orion_holepunch_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HolePunchingEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_orion_holepunch_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*HolePunchingEvent_InitializationResponse)(nil),
		(*HolePunchingEvent_Complete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_orion_holepunch_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_orion_holepunch_proto_goTypes,
		DependencyIndexes: file_proto_orion_holepunch_proto_depIdxs,
		MessageInfos:      file_proto_orion_holepunch_proto_msgTypes,
	}.Build()
	File_proto_orion_holepunch_proto = out.File
	file_proto_orion_holepunch_proto_rawDesc = nil
	file_proto_orion_holepunch_proto_goTypes = nil
	file_proto_orion_holepunch_proto_depIdxs = nil
}
