// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.2
// source: proto/orion_registry.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RegistryClient is the client API for Registry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegistryClient interface {
	// Subscribe to the event stream
	SubscribeToStream(ctx context.Context, opts ...grpc.CallOption) (Registry_SubscribeToStreamClient, error)
}

type registryClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistryClient(cc grpc.ClientConnInterface) RegistryClient {
	return &registryClient{cc}
}

func (c *registryClient) SubscribeToStream(ctx context.Context, opts ...grpc.CallOption) (Registry_SubscribeToStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Registry_ServiceDesc.Streams[0], "/Registry/SubscribeToStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &registrySubscribeToStreamClient{stream}
	return x, nil
}

type Registry_SubscribeToStreamClient interface {
	Send(*RPCClientEvent) error
	Recv() (*RPCServerEvent, error)
	grpc.ClientStream
}

type registrySubscribeToStreamClient struct {
	grpc.ClientStream
}

func (x *registrySubscribeToStreamClient) Send(m *RPCClientEvent) error {
	return x.ClientStream.SendMsg(m)
}

func (x *registrySubscribeToStreamClient) Recv() (*RPCServerEvent, error) {
	m := new(RPCServerEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RegistryServer is the server API for Registry service.
// All implementations must embed UnimplementedRegistryServer
// for forward compatibility
type RegistryServer interface {
	// Subscribe to the event stream
	SubscribeToStream(Registry_SubscribeToStreamServer) error
	mustEmbedUnimplementedRegistryServer()
}

// UnimplementedRegistryServer must be embedded to have forward compatible implementations.
type UnimplementedRegistryServer struct {
}

func (UnimplementedRegistryServer) SubscribeToStream(Registry_SubscribeToStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeToStream not implemented")
}
func (UnimplementedRegistryServer) mustEmbedUnimplementedRegistryServer() {}

// UnsafeRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistryServer will
// result in compilation errors.
type UnsafeRegistryServer interface {
	mustEmbedUnimplementedRegistryServer()
}

func RegisterRegistryServer(s grpc.ServiceRegistrar, srv RegistryServer) {
	s.RegisterService(&Registry_ServiceDesc, srv)
}

func _Registry_SubscribeToStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RegistryServer).SubscribeToStream(&registrySubscribeToStreamServer{stream})
}

type Registry_SubscribeToStreamServer interface {
	Send(*RPCServerEvent) error
	Recv() (*RPCClientEvent, error)
	grpc.ServerStream
}

type registrySubscribeToStreamServer struct {
	grpc.ServerStream
}

func (x *registrySubscribeToStreamServer) Send(m *RPCServerEvent) error {
	return x.ServerStream.SendMsg(m)
}

func (x *registrySubscribeToStreamServer) Recv() (*RPCClientEvent, error) {
	m := new(RPCClientEvent)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Registry_ServiceDesc is the grpc.ServiceDesc for Registry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Registry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Registry",
	HandlerType: (*RegistryServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeToStream",
			Handler:       _Registry_SubscribeToStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/orion_registry.proto",
}
