// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.27.2
// source: proto/orion_registry.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Data sent by a client to initialize an orion membership session
type InitializeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendlyName    string `protobuf:"bytes,1,opt,name=friendly_name,json=friendlyName,proto3" json:"friendly_name,omitempty"`
	TimestampSigned int64  `protobuf:"varint,2,opt,name=timestamp_signed,json=timestampSigned,proto3" json:"timestamp_signed,omitempty"`
	Signed          []byte `protobuf:"bytes,3,opt,name=signed,proto3" json:"signed,omitempty"`
	MemberId        int64  `protobuf:"varint,4,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Certificate     []byte `protobuf:"bytes,5,opt,name=certificate,proto3" json:"certificate,omitempty"`
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_orion_registry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orion_registry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_proto_orion_registry_proto_rawDescGZIP(), []int{0}
}

func (x *InitializeRequest) GetFriendlyName() string {
	if x != nil {
		return x.FriendlyName
	}
	return ""
}

func (x *InitializeRequest) GetTimestampSigned() int64 {
	if x != nil {
		return x.TimestampSigned
	}
	return 0
}

func (x *InitializeRequest) GetSigned() []byte {
	if x != nil {
		return x.Signed
	}
	return nil
}

func (x *InitializeRequest) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *InitializeRequest) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

// Event sent to all clients when a new orion session is initialized.
type ClientNewOnNetworkEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendlyName string `protobuf:"bytes,1,opt,name=friendly_name,json=friendlyName,proto3" json:"friendly_name,omitempty"`
	PeerId       int64  `protobuf:"varint,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
}

func (x *ClientNewOnNetworkEvent) Reset() {
	*x = ClientNewOnNetworkEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_orion_registry_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientNewOnNetworkEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientNewOnNetworkEvent) ProtoMessage() {}

func (x *ClientNewOnNetworkEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orion_registry_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientNewOnNetworkEvent.ProtoReflect.Descriptor instead.
func (*ClientNewOnNetworkEvent) Descriptor() ([]byte, []int) {
	return file_proto_orion_registry_proto_rawDescGZIP(), []int{1}
}

func (x *ClientNewOnNetworkEvent) GetFriendlyName() string {
	if x != nil {
		return x.FriendlyName
	}
	return ""
}

func (x *ClientNewOnNetworkEvent) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

// Event sent to a client when another clients when a clients wants to initiate a peer-to-peer link.
type ClientWantsToInitiateLinkEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendlyName string `protobuf:"bytes,1,opt,name=friendly_name,json=friendlyName,proto3" json:"friendly_name,omitempty"`
	PeerId       int64  `protobuf:"varint,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
}

func (x *ClientWantsToInitiateLinkEvent) Reset() {
	*x = ClientWantsToInitiateLinkEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_orion_registry_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientWantsToInitiateLinkEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientWantsToInitiateLinkEvent) ProtoMessage() {}

func (x *ClientWantsToInitiateLinkEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orion_registry_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientWantsToInitiateLinkEvent.ProtoReflect.Descriptor instead.
func (*ClientWantsToInitiateLinkEvent) Descriptor() ([]byte, []int) {
	return file_proto_orion_registry_proto_rawDescGZIP(), []int{2}
}

func (x *ClientWantsToInitiateLinkEvent) GetFriendlyName() string {
	if x != nil {
		return x.FriendlyName
	}
	return ""
}

func (x *ClientWantsToInitiateLinkEvent) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

// Sent when a clients lost connection and needs to be completely kicked from the network.
type ClientDisconnectedTeardownEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendlyName string `protobuf:"bytes,1,opt,name=friendly_name,json=friendlyName,proto3" json:"friendly_name,omitempty"`
	PeerId       int64  `protobuf:"varint,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
}

func (x *ClientDisconnectedTeardownEvent) Reset() {
	*x = ClientDisconnectedTeardownEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_orion_registry_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientDisconnectedTeardownEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDisconnectedTeardownEvent) ProtoMessage() {}

func (x *ClientDisconnectedTeardownEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orion_registry_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDisconnectedTeardownEvent.ProtoReflect.Descriptor instead.
func (*ClientDisconnectedTeardownEvent) Descriptor() ([]byte, []int) {
	return file_proto_orion_registry_proto_rawDescGZIP(), []int{3}
}

func (x *ClientDisconnectedTeardownEvent) GetFriendlyName() string {
	if x != nil {
		return x.FriendlyName
	}
	return ""
}

func (x *ClientDisconnectedTeardownEvent) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

type RPCEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//
	//	*RPCEvent_ClientNewOnNetworkEvent
	//	*RPCEvent_ClientWantsToInitiateLinkEvent
	//	*RPCEvent_ClientDisconnectedTeardownEvent
	Event isRPCEvent_Event `protobuf_oneof:"event"`
}

func (x *RPCEvent) Reset() {
	*x = RPCEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_orion_registry_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCEvent) ProtoMessage() {}

func (x *RPCEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orion_registry_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCEvent.ProtoReflect.Descriptor instead.
func (*RPCEvent) Descriptor() ([]byte, []int) {
	return file_proto_orion_registry_proto_rawDescGZIP(), []int{4}
}

func (m *RPCEvent) GetEvent() isRPCEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *RPCEvent) GetClientNewOnNetworkEvent() *ClientNewOnNetworkEvent {
	if x, ok := x.GetEvent().(*RPCEvent_ClientNewOnNetworkEvent); ok {
		return x.ClientNewOnNetworkEvent
	}
	return nil
}

func (x *RPCEvent) GetClientWantsToInitiateLinkEvent() *ClientWantsToInitiateLinkEvent {
	if x, ok := x.GetEvent().(*RPCEvent_ClientWantsToInitiateLinkEvent); ok {
		return x.ClientWantsToInitiateLinkEvent
	}
	return nil
}

func (x *RPCEvent) GetClientDisconnectedTeardownEvent() *ClientDisconnectedTeardownEvent {
	if x, ok := x.GetEvent().(*RPCEvent_ClientDisconnectedTeardownEvent); ok {
		return x.ClientDisconnectedTeardownEvent
	}
	return nil
}

type isRPCEvent_Event interface {
	isRPCEvent_Event()
}

type RPCEvent_ClientNewOnNetworkEvent struct {
	ClientNewOnNetworkEvent *ClientNewOnNetworkEvent `protobuf:"bytes,1,opt,name=client_new_on_network_event,json=clientNewOnNetworkEvent,proto3,oneof"`
}

type RPCEvent_ClientWantsToInitiateLinkEvent struct {
	ClientWantsToInitiateLinkEvent *ClientWantsToInitiateLinkEvent `protobuf:"bytes,2,opt,name=client_wants_to_initiate_link_event,json=clientWantsToInitiateLinkEvent,proto3,oneof"`
}

type RPCEvent_ClientDisconnectedTeardownEvent struct {
	ClientDisconnectedTeardownEvent *ClientDisconnectedTeardownEvent `protobuf:"bytes,3,opt,name=client_disconnected_teardown_event,json=clientDisconnectedTeardownEvent,proto3,oneof"`
}

func (*RPCEvent_ClientNewOnNetworkEvent) isRPCEvent_Event() {}

func (*RPCEvent_ClientWantsToInitiateLinkEvent) isRPCEvent_Event() {}

func (*RPCEvent_ClientDisconnectedTeardownEvent) isRPCEvent_Event() {}

// Send to a peer to indicate that another connection is possible to
// the specified.
type InitializeConnectionToPeerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemberId     string `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Endpoint     string `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	PublicKey    string `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PresharedKey string `protobuf:"bytes,4,opt,name=preshared_key,json=presharedKey,proto3" json:"preshared_key,omitempty"`
}

func (x *InitializeConnectionToPeerRequest) Reset() {
	*x = InitializeConnectionToPeerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_orion_registry_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitializeConnectionToPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeConnectionToPeerRequest) ProtoMessage() {}

func (x *InitializeConnectionToPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orion_registry_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeConnectionToPeerRequest.ProtoReflect.Descriptor instead.
func (*InitializeConnectionToPeerRequest) Descriptor() ([]byte, []int) {
	return file_proto_orion_registry_proto_rawDescGZIP(), []int{5}
}

func (x *InitializeConnectionToPeerRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *InitializeConnectionToPeerRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *InitializeConnectionToPeerRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *InitializeConnectionToPeerRequest) GetPresharedKey() string {
	if x != nil {
		return x.PresharedKey
	}
	return ""
}

// Response to a connection request.
type InitializeConnectionToPeerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitializeConnectionToPeerResponse) Reset() {
	*x = InitializeConnectionToPeerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_orion_registry_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitializeConnectionToPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeConnectionToPeerResponse) ProtoMessage() {}

func (x *InitializeConnectionToPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orion_registry_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeConnectionToPeerResponse.ProtoReflect.Descriptor instead.
func (*InitializeConnectionToPeerResponse) Descriptor() ([]byte, []int) {
	return file_proto_orion_registry_proto_rawDescGZIP(), []int{6}
}

var File_proto_orion_registry_proto protoreflect.FileDescriptor

var file_proto_orion_registry_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x72, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xba, 0x01, 0x0a,
	0x11, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x6c, 0x79, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x6c, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x53, 0x69, 0x67, 0x6e,
	0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x63, 0x65,
	0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x22, 0x57, 0x0a, 0x17, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x4e, 0x65, 0x77, 0x4f, 0x6e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x6c, 0x79,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x6c, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x5e, 0x0a, 0x1e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x57, 0x61, 0x6e, 0x74,
	0x73, 0x54, 0x6f, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x6c, 0x79,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x6c, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x5f, 0x0a, 0x1f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x54, 0x65, 0x61, 0x72, 0x64, 0x6f, 0x77, 0x6e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x6c,
	0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x6c, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x65, 0x65,
	0x72, 0x49, 0x64, 0x22, 0xce, 0x02, 0x0a, 0x08, 0x52, 0x50, 0x43, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x58, 0x0a, 0x1b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x65, 0x77, 0x5f, 0x6f,
	0x6e, 0x5f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4e, 0x65,
	0x77, 0x4f, 0x6e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48,
	0x00, 0x52, 0x17, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4e, 0x65, 0x77, 0x4f, 0x6e, 0x4e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x6e, 0x0a, 0x23, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x5f, 0x77, 0x61, 0x6e, 0x74, 0x73, 0x5f, 0x74, 0x6f, 0x5f, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x57, 0x61, 0x6e, 0x74, 0x73, 0x54, 0x6f, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x65, 0x4c,
	0x69, 0x6e, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x1e, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x57, 0x61, 0x6e, 0x74, 0x73, 0x54, 0x6f, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74,
	0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x6f, 0x0a, 0x22, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x5f, 0x74, 0x65, 0x61, 0x72, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44,
	0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x54, 0x65, 0x61, 0x72, 0x64,
	0x6f, 0x77, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x1f, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x54, 0x65,
	0x61, 0x72, 0x64, 0x6f, 0x77, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x22, 0xa0, 0x01, 0x0a, 0x21, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c,
	0x69, 0x7a, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x50,
	0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d,
	0x65, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x65, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x65, 0x73, 0x68,
	0x61, 0x72, 0x65, 0x64, 0x4b, 0x65, 0x79, 0x22, 0x24, 0x0a, 0x22, 0x49, 0x6e, 0x69, 0x74, 0x69,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x6f, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xa7, 0x01,
	0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x12, 0x34, 0x0a, 0x11, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x54, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12,
	0x12, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x52, 0x50, 0x43, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x30, 0x01,
	0x12, 0x65, 0x0a, 0x1a, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x50, 0x65, 0x65, 0x72, 0x12, 0x22,
	0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x23, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x50, 0x65, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_orion_registry_proto_rawDescOnce sync.Once
	file_proto_orion_registry_proto_rawDescData = file_proto_orion_registry_proto_rawDesc
)

func file_proto_orion_registry_proto_rawDescGZIP() []byte {
	file_proto_orion_registry_proto_rawDescOnce.Do(func() {
		file_proto_orion_registry_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_orion_registry_proto_rawDescData)
	})
	return file_proto_orion_registry_proto_rawDescData
}

var file_proto_orion_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_orion_registry_proto_goTypes = []interface{}{
	(*InitializeRequest)(nil),                  // 0: InitializeRequest
	(*ClientNewOnNetworkEvent)(nil),            // 1: ClientNewOnNetworkEvent
	(*ClientWantsToInitiateLinkEvent)(nil),     // 2: ClientWantsToInitiateLinkEvent
	(*ClientDisconnectedTeardownEvent)(nil),    // 3: ClientDisconnectedTeardownEvent
	(*RPCEvent)(nil),                           // 4: RPCEvent
	(*InitializeConnectionToPeerRequest)(nil),  // 5: InitializeConnectionToPeerRequest
	(*InitializeConnectionToPeerResponse)(nil), // 6: InitializeConnectionToPeerResponse
}
var file_proto_orion_registry_proto_depIdxs = []int32{
	1, // 0: RPCEvent.client_new_on_network_event:type_name -> ClientNewOnNetworkEvent
	2, // 1: RPCEvent.client_wants_to_initiate_link_event:type_name -> ClientWantsToInitiateLinkEvent
	3, // 2: RPCEvent.client_disconnected_teardown_event:type_name -> ClientDisconnectedTeardownEvent
	0, // 3: Registry.SubscribeToStream:input_type -> InitializeRequest
	5, // 4: Registry.InitializeConnectionToPeer:input_type -> InitializeConnectionToPeerRequest
	4, // 5: Registry.SubscribeToStream:output_type -> RPCEvent
	6, // 6: Registry.InitializeConnectionToPeer:output_type -> InitializeConnectionToPeerResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_orion_registry_proto_init() }
func file_proto_orion_registry_proto_init() {
	if File_proto_orion_registry_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_orion_registry_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitializeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_orion_registry_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientNewOnNetworkEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_orion_registry_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientWantsToInitiateLinkEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_orion_registry_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientDisconnectedTeardownEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_orion_registry_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPCEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_orion_registry_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitializeConnectionToPeerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_orion_registry_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitializeConnectionToPeerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_orion_registry_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*RPCEvent_ClientNewOnNetworkEvent)(nil),
		(*RPCEvent_ClientWantsToInitiateLinkEvent)(nil),
		(*RPCEvent_ClientDisconnectedTeardownEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_orion_registry_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_orion_registry_proto_goTypes,
		DependencyIndexes: file_proto_orion_registry_proto_depIdxs,
		MessageInfos:      file_proto_orion_registry_proto_msgTypes,
	}.Build()
	File_proto_orion_registry_proto = out.File
	file_proto_orion_registry_proto_rawDesc = nil
	file_proto_orion_registry_proto_goTypes = nil
	file_proto_orion_registry_proto_depIdxs = nil
}
