// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.2
// source: proto/orion_registry.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RegistryClient is the client API for Registry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegistryClient interface {
	// Subscribe to the event stream
	SubscribeToStream(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (Registry_SubscribeToStreamClient, error)
	// When an existing client wants to initiate a connection to a new or existing peer.
	InitializeConnectionToPeer(ctx context.Context, in *InitializeConnectionToPeerRequest, opts ...grpc.CallOption) (*InitializeConnectionToPeerResponse, error)
}

type registryClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistryClient(cc grpc.ClientConnInterface) RegistryClient {
	return &registryClient{cc}
}

func (c *registryClient) SubscribeToStream(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (Registry_SubscribeToStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Registry_ServiceDesc.Streams[0], "/Registry/SubscribeToStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &registrySubscribeToStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Registry_SubscribeToStreamClient interface {
	Recv() (*RPCEvent, error)
	grpc.ClientStream
}

type registrySubscribeToStreamClient struct {
	grpc.ClientStream
}

func (x *registrySubscribeToStreamClient) Recv() (*RPCEvent, error) {
	m := new(RPCEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *registryClient) InitializeConnectionToPeer(ctx context.Context, in *InitializeConnectionToPeerRequest, opts ...grpc.CallOption) (*InitializeConnectionToPeerResponse, error) {
	out := new(InitializeConnectionToPeerResponse)
	err := c.cc.Invoke(ctx, "/Registry/InitializeConnectionToPeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryServer is the server API for Registry service.
// All implementations must embed UnimplementedRegistryServer
// for forward compatibility
type RegistryServer interface {
	// Subscribe to the event stream
	SubscribeToStream(*InitializeRequest, Registry_SubscribeToStreamServer) error
	// When an existing client wants to initiate a connection to a new or existing peer.
	InitializeConnectionToPeer(context.Context, *InitializeConnectionToPeerRequest) (*InitializeConnectionToPeerResponse, error)
	mustEmbedUnimplementedRegistryServer()
}

// UnimplementedRegistryServer must be embedded to have forward compatible implementations.
type UnimplementedRegistryServer struct {
}

func (UnimplementedRegistryServer) SubscribeToStream(*InitializeRequest, Registry_SubscribeToStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeToStream not implemented")
}
func (UnimplementedRegistryServer) InitializeConnectionToPeer(context.Context, *InitializeConnectionToPeerRequest) (*InitializeConnectionToPeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitializeConnectionToPeer not implemented")
}
func (UnimplementedRegistryServer) mustEmbedUnimplementedRegistryServer() {}

// UnsafeRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistryServer will
// result in compilation errors.
type UnsafeRegistryServer interface {
	mustEmbedUnimplementedRegistryServer()
}

func RegisterRegistryServer(s grpc.ServiceRegistrar, srv RegistryServer) {
	s.RegisterService(&Registry_ServiceDesc, srv)
}

func _Registry_SubscribeToStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InitializeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RegistryServer).SubscribeToStream(m, &registrySubscribeToStreamServer{stream})
}

type Registry_SubscribeToStreamServer interface {
	Send(*RPCEvent) error
	grpc.ServerStream
}

type registrySubscribeToStreamServer struct {
	grpc.ServerStream
}

func (x *registrySubscribeToStreamServer) Send(m *RPCEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _Registry_InitializeConnectionToPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeConnectionToPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).InitializeConnectionToPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Registry/InitializeConnectionToPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).InitializeConnectionToPeer(ctx, req.(*InitializeConnectionToPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Registry_ServiceDesc is the grpc.ServiceDesc for Registry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Registry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Registry",
	HandlerType: (*RegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitializeConnectionToPeer",
			Handler:    _Registry_InitializeConnectionToPeer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeToStream",
			Handler:       _Registry_SubscribeToStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/orion_registry.proto",
}
