# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  # Build for the `oriond` daemon
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    main: ./bin/oriond
    id: "oriond"
    binary: oriond
    # Custom ldflags.
    #
    # Default: '-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser'.
    # Templates: allowed.
    ldflags:
      - s -w -X internal.Version={{.Version}} -X internal.Commit={{.Commit}} -X internal.Date={{.Date}} -X internal.BuiltBy=goreleaser
  # Build for the `orion-registry` daemon
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    main: ./bin/registry
    id: "registry"
    binary: orion-registry
archives: []
nfpms:
  - id: orion-backbone
    package_name: orion-backbone
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: Matthieu Pignolet
    homepage: https://mpgn.dev/
    maintainer: Matthieu Pignolet <orion-release@mpgn.dev>
    license: Apache 2.0
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    umask: 0o002
    dependencies:
      - wireguard
      - frr
    bindir: /usr/bin

    scripts:
      postinstall: ./packaging/postinstall.sh

    # Version Release.
    release: 1

    # Section.
    section: default

    # Priority.
    priority: extra
    meta: false

    # Contents to add to the package.
    # GoReleaser will automatically add the binaries.
    contents:
      # Service files
      - src: packaging/orion-registry.service
        dst: /etc/systemd/system/orion-registry.service
        type: "config|noreplace"
      - src: packaging/oriond.service
        dst: /etc/systemd/system/oriond.service
        type: "config|noreplace"
      # Default files
      - src: packaging/oriond
        dst: /etc/default/oriond
        type: "config|noreplace"
      - src: packaging/orion-registry
        dst: /etc/default/orion-registry
        type: "config|noreplace"
      - src: packaging/frr.conf.tmpl
        dst: /etc/oriond/frr.conf.tmpl
        type: "config|noreplace"
      # Root CA
      - src: packaging/ca.crt
        dst: /etc/oriond/
        type: "config|noreplace"

    # Custom configuration applied only to the RPM packager.
    rpm:
      summary: OrionV3 is the backbone for the Orion Network

    # Custom configuration applied only to the Deb packager.
    deb:
      fields:
        Bugs: https://github.com/MatthieuCoder/OrionV3

    apk:
      signature:
        key_name: origin

    archlinux:
      pkgbase: orion-registry
      packager: Matthieu Pignolet <orion-release@mpgn.dev>
